# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Deploying w docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
        - name: latest
          cntr: gvegayon/rmd-basic:latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${{ matrix.cntr }}

      - name: SessionInfo
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${{ matrix.cntr }} R -q -e 'sessionInfo()'

      - name: Build
        run: docker run --rm -i -v $(pwd):/mnt -w /mnt -e CI=true ${{ matrix.cntr }} Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m 'Re-build Rmarkdown files'
          git push origin || echo "No changes to commit"

